global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: "rust-service"
    static_configs:
      - targets: ["rust-service:8082"]
    metrics_path: /metrics

  - job_name: "go-service"
    static_configs:
      - targets: ["go-service:8082"]
    metrics_path: /metrics
