// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// source: tick.proto

package tick

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// TickServiceClient is the client API for TickService service.
type TickServiceClient interface {
	ProcessTick(ctx context.Context, in *TickRequest, opts ...grpc.CallOption) (*TickResponse, error)
}

type tickServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTickServiceClient(cc grpc.ClientConnInterface) TickServiceClient {
	return &tickServiceClient{cc}
}

func (c *tickServiceClient) ProcessTick(ctx context.Context, in *TickRequest, opts ...grpc.CallOption) (*TickResponse, error) {
	out := new(TickResponse)
	err := c.cc.Invoke(ctx, "/tick.TickService/ProcessTick", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TickServiceServer is the server API for TickService service.
type TickServiceServer interface {
	ProcessTick(context.Context, *TickRequest) (*TickResponse, error)
	mustEmbedUnimplementedTickServiceServer()
}

// UnimplementedTickServiceServer should be embedded to have forward compatible implementations.
type UnimplementedTickServiceServer struct{}

func (UnimplementedTickServiceServer) ProcessTick(context.Context, *TickRequest) (*TickResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ProcessTick not implemented")
}
func (UnimplementedTickServiceServer) mustEmbedUnimplementedTickServiceServer() {}

// UnsafeTickServiceServer may be embedded to opt out of forward compatibility for this service.
type UnsafeTickServiceServer interface {
	mustEmbedUnimplementedTickServiceServer()
}

func RegisterTickServiceServer(s grpc.ServiceRegistrar, srv TickServiceServer) {
	s.RegisterService(&TickService_ServiceDesc, srv)
}

func _TickService_ProcessTick_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TickRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TickServiceServer).ProcessTick(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tick.TickService/ProcessTick",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TickServiceServer).ProcessTick(ctx, req.(*TickRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TickService_ServiceDesc is the grpc.ServiceDesc for TickService service.
var TickService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "tick.TickService",
	HandlerType: (*TickServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ProcessTick",
			Handler:    _TickService_ProcessTick_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "tick.proto",
}
